name: Translate Kotygoroshko

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages
      - name: Kotygoroshko - English
        uses: OstrikovG/translate-readme@main
        with:
          LANG: en